version: 0.2

phases:
  pre_build:
    commands:
      - cd ec2-test-repo
      - pwd
      - echo Running JUnit tests on `date`
      - mvn -version
      - mvn install:install-file -Dfile=C:\\OracleJDBC\\ojdbc7.jar 
           -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0 -Dpackaging=jar
  
  build:
    commands:
      - echo Maven build started on `date`
      - mvn clean package
      - mv target/ec2-test-repo-0.0.1-SNAPSHOT.war ec2-test-repo-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - ec2-test-repo-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
eb_codebuild_settings:
  CodeBuildServiceRole: codebuild-codebuild-test-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/java:openjdk-8
  Timeout: 60
  base-directory: 'target/ec2-test-repo'